version: '3.6'
services:
  sonarqube:
    image: sonarqube:9.0.1-community
    container_name: sonarqube
    ports:
      - 9000:9000
      - 9092:9092
    networks:
      - common

networks:
  common:
    external: true
